[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mypkgs"
version = "0.1.0"
description = "Simple util to view manually installed packages on Debian"
authors = [
    { name = "Alexandr Negrya", email = "alexandr.negrya@gmail.com" },
]